import { mkdir, copyFile, rm, readdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const target=path.join(root,'public');
await rm(target,{recursive:true,force:true});
await mkdir(path.join(target,'assets'),{recursive:true});
const files=['index.html','styles.css','app.js','ui-model.js','engine.js','favicon.svg','league.js','league.css','league-game.js','privacy.html','_headers'];
for(const file of files)await copyFile(path.join(root,file),path.join(target,file));
await mkdir(path.join(target,'assets/fonts'),{recursive:true});
const fonts=(await readdir(path.join(root,'assets/fonts'))).filter(name=>/\.(woff2|css|txt)$/.test(name));
for(const name of fonts)await copyFile(path.join(root,'assets/fonts',name),path.join(target,'assets/fonts',name));
console.log('Built '+(files.length+fonts.length)+' public assets. Backend, tests and local settings are excluded.');
